[server]
hosts = 0.0.0.0:5232
max_content_length = 16777216
max_resource_size = 2097152
[auth]
type = http_x_remote_user
[rights]
type = owner_only
permit_delete_collection = False
permit_overwrite_collection = False
[storage]
filesystem_folder = /data/collections
[web]
type = none
[logging]
level = warning
